// <auto-generated />
namespace collectible_figures.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class collectiblefigures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(collectiblefigures));
        
        string IMigrationMetadata.Id
        {
            get { return "201901062254449_collectible-figures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
